version: "3"
services:
  postgres:
    build: ./postgres-dev
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_LIST: milo_dev

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   ports:
  #     - 8090:8080
  #   environment:
  #     ADMINER_DEFAULT_SERVER: postgres
      